# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmxAS4g1z-lNynECvmrRFrtlH1PZUa8O
"""

a="Devi"
b=3
c=a*b
print(c)

#explicit type conversion from string to integer only one character is supported
a="D"
b=ord(a)
print((b))

#Print statement
print("Hello world")
print ("I am practicing programming in Coding Ninjas")

#use of end parameter
#In python newline character is by default
#To stop printing in newline we use end
print("Hello Devisrinivas ",end='')
print("Keep Trying hard, you can do it",end='')

"""**Print syntax** print(object(s),sep=seperator,end=end,file=file,flush=flush)"""

#use of end
print("Devisrinivas",end='@')
print("Chakri")

#Seperator
print('03','12','2003',sep='-')